import 'details.dart';

final detailsList = [
  Detail(
      title: "Chernobyl",
      description:
          "Chernobyl is a historical drama television miniseries created and produced by HBO in association with Sky UK, depicting the Chernobyl nuclear disaster of April 1986 and the unprecedented cleanup efforts that followed.",
      rating: 9.6,
      stream: "Hotstar",
      status: "Completed",
      seasons: 1,
      genre: "Drama, History",
      url: "https://www.hotstar.com/tv/chernobyl/s-2146",
      vid: "s9APLXM9Ei8"),
  Detail(
      title: "Breaking Bad",
      description:
          "Walter White, a chemistry teacher, discovers that he has cancer and decides to get into the meth-making business to repay his medical debts. His priorities begin to change when he partners with Jesse.",
      rating: 9.5,
      stream: "Netflix",
      status: "Completed",
      seasons: 5,
      genre: "Crime, Drama, Thriller",
      url: "https://www.netflix.com/title/70143836",
      vid: "HhesaQXLuRY"),
  Detail(
      title: "Band of Brothers",
      description:
          "The story of Easy Company, 506th Regiment of the 101st Airborne Division from 1942 to the end of World War II. A collection of fifty portraits illustrated by archive footage and recounted in voice.",
      rating: 9.5,
      stream: "Hotstar",
      status: "Completed",
      seasons: 1,
      genre: "Drama, Action, History",
      url: "https://www.hotstar.com/tv/band-of-brothers/s-507",
      vid: "kyDkHvi9yeI"),
  Detail(
      title: "Game of Thrones",
      description:
          "Nine noble families wage war against each other in order to gain control over the mythical land of Westeros. Meanwhile, a force is rising after millenniums and threatens the existence of living men.",
      rating: 9.4,
      stream: "Hotstar",
      status: "Completed",
      seasons: 8,
      genre: "Drama, Adventure",
      url: "https://www.hotstar.com/tv/game-of-thrones/s-510",
      vid: "BpJYNVhGf1s"),
  Detail(
      title: "The Wire",
      description:
          "In the city of Baltimore, Detective James McNulty and his team investigate crimes and try their best to solve the bridge that exists between the drug kingpins and the law enforcement agencies.",
      rating: 9.3,
      stream: "Hotstar",
      status: "Completed",
      seasons: 5,
      genre: "Crime, Drama, Thriller",
      url: "https://www.hotstar.com/tv/the-wire/s-527",
      vid: "9qK-VGjMr8g"),
  Detail(
      title: "Rick and Morty",
      description:
          "An animated series that follows the exploits of a super scientist and his not-so-bright grandson.",
      rating: 9.2,
      stream: "Netflix",
      status: "Ongoing",
      seasons: 4,
      genre: "Animation,Comedy,Adventure",
      url: "https://www.netflix.com/title/80014749",
      vid: "WNhH00OIPP0"),
  Detail(
      title: "Avatar:The Last Airbender",
      description:
          "The world is divided into four nations -- the Water Tribe, the Earth Kingdom, the Fire Nation and and the Air Nomads -- each represented by a natural element for which the nation is named. Benders have the ability to control and manipulate the element from their nation. Only the Avatar is the master of all four elements. The ruthless Fire Nation wants to conquer the world but the only bender who has enough power, the Avatar, has disappeared ... until now. His tribe soon discovers that Aang is the long-lost Avatar. Now Katara and Sokka must safeguard Aang on his journey to master all four elements and save the world from the Fire Nation.",
      rating: 9.2,
      stream: "Torrent",
      status: "Completed",
      seasons: 3,
      genre: " Animation, Action, Adventure",
      url: "",
      vid: "B14pPZ1AlbI"),
  Detail(
      title: "The Sopranos",
      description:
          "New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life that affect his mental state, leading him to seek professional psychiatric counseling.",
      rating: 9.2,
      stream: "Hotstar",
      status: "Completed",
      seasons: 6,
      genre: "Crime, Drama",
      url: "https://www.hotstar.com/tv/the-sopranos/s-934",
      vid: "wrN2k3qGbVA"),
  Detail(
      title: "Sherlock",
      description:
          "Dr. Watson, a former army doctor, finds himself sharing a flat with Sherlock Holmes, an eccentric individual with a knack for solving crimes. Together, they take on the most unusual cases.",
      rating: 9.1,
      stream: "Netflix",
      status: "Ongoing",
      seasons: 4,
      genre: " Crime, Drama, Mystery",
      url: "https://www.netflix.com/title/70202589",
      vid: "xK7S9mrFWL4"),
  Detail(
      title: "Death Note",
      description:
          "An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written into it.",
      rating: 9.0,
      stream: "Netflix",
      status: "Completed",
      seasons: 1,
      genre: " Animation,Suspense,Chilling",
      url: "https://www.netflix.com/title/70204970",
      vid: "HK3lkfhX_XY"),
  Detail(
      title: "Firefly",
      description:
          "Five hundred years in the future, a renegade crew aboard a small spacecraft tries to survive as they travel the unknown parts of the galaxy and evade warring factions as well as authority agents out to get them.",
      rating: 9.0,
      stream: "Torrents",
      status: "Completed",
      seasons: 1,
      genre: " Adventure, Drama, Sci-Fi",
      url: "",
      vid: "mEx6UpiIKM4"),
  Detail(
      title: "True Detective",
      description:
          "Police officers and detectives around the USA are forced to face dark secrets about themselves and the people around them while investigating homicides.",
      rating: 9.0,
      stream: "Hotstar",
      status: "Ongoing",
      seasons: 3,
      genre: "Crime, Mystery, Anthology",
      url: "https://www.hotstar.com/tv/true-detective/s-528",
      vid: "fVQUcaO4AvE"),
  Detail(
      title: "Fargo",
      description:
          "Various chronicles of deception, intrigue and murder in and around frozen Minnesota. Yet all of these tales mysteriously lead back one way or another to Fargo, North Dakota.",
      rating: 9,
      stream: "Netflix",
      status: "Ongoing",
      seasons: 4,
      genre: "Drama, Action, History",
      url: "https://www.netflix.com/watch/70285785",
      vid: "etgvHG3w48"),
  Detail(
      title: "Black Mirror",
      description:
          "An anthology series exploring a twisted, high-tech world where humanity's greatest innovations and darkest instincts collide.",
      rating: 8.9,
      stream: "Netflix",
      status: "Ongoing",
      seasons: 5,
      genre: "Drama, Sci-Fi, Thriller ",
      url: "https://www.netflix.com/title/70264888",
      vid: "nSDviEdvw4U"),
  Detail(
      title: "Stranger Things",
      description:
          "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying forces in order to get him back.",
      rating: 8.9,
      stream: "Netflix",
      status: "Ongoing",
      seasons: 3,
      genre: "Drama, Fantasy, Horror",
      url: "https://www.netflix.com/title/80057281",
      vid: "mnd7sFt5c3A"),
  Detail(
      title: "F.R.I.E.N.D.S",
      description:
          "Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.",
      rating: 8.9,
      stream: "Netflix",
      status: "Completed",
      seasons: 10,
      genre: "Comedy, Sitcom",
      url: "https://www.netflix.com/title/70153404",
      vid: "Eibl9JIpcKk"),
  Detail(
      title: "Westworld",
      description:
          "In a futuristic Western-themed amusement park, Westworld, the visitors interact with automatons. However, all hell breaks loose when the robots begin malfunctioning.",
      rating: 8.8,
      stream: "Hotstar",
      status: "Ongoing",
      seasons: 3,
      genre: "Drama, Mystery, Sci-Fi",
      url: "https://www.hotstar.com/tv/westworld/s-825",
      vid: "kEkZdgWu7mM"),
  Detail(
      title: "The Office US",
      description:
          "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
      rating: 8.8,
      stream: "Prime Video",
      status: "Completed",
      seasons: 9,
      genre: "Crime, Drama",
      url:
          "https://www.primevideo.com/detail/The-Office/0H7JFOPK2QO9WVZ8D9D0J5ZRQN",
      vid: "jz1omRneAGg"),
  Detail(
      title: "Arrested Development",
      description:
          "Level-headed son Michael Bluth takes over family affairs after his father is imprisoned. But the rest of his spoiled, dysfunctional family are making his job unbearable.",
      rating: 8.8,
      stream: "Hotstar",
      status: "Completed",
      seasons: 5,
      genre: "Comedy",
      url: "https://www.hotstar.com/tv/arrested-development/s-913",
      vid: "KnXl4m0-72k"),
  Detail(
      title: "Peaky Blinders",
      description:
          "A dangerous Tommy Shelby leads Peaky Blinders, a criminal gang based in Birmingham in 1919. Chief Inspector Chester Campbell decides to nab him and put an end to the activities of this gang.",
      rating: 8.8,
      stream: "Netflix",
      status: "Ongoing",
      seasons: 5,
      genre: "Crime, Drama",
      url: "https://www.netflix.com/title/80003008",
      vid: "oVzVdvGIC7U"),
  Detail(
      title: "Narcos",
      description:
          "Netflix chronicles the rise of the cocaine trade in Colombia and the gripping real-life stories of drug kingpins of the late '80s in this raw, gritty original series. Also detailed are the actions taken by law enforcement as they battle in the war on drugs, targeting notorious and powerful figures that include drug lord Pablo Escobar. As efforts are made to control cocaine, one of the world's most valuable commodities, the many entities involved -- legal, political, police, military and civilian -- find themselves in conflict.",
      rating: 8.8,
      stream: "Netflix",
      status: "Completed",
      seasons: 3,
      genre: "Biography, Crime, Drama",
      url: "https://www.netflix.com/title/80025172",
      vid: "RNWAKZzgbp4"),
  Detail(
      title: "House of Cards",
      description:
          "Frank Underwood is a Democrat appointed as the secretary of state. Along with his wife, he sets out on a quest to seek revenge on the people who betrayed him while successfully rising to supremacy.",
      rating: 8.8,
      stream: "Netflix",
      status: "Completed",
      seasons: 6,
      genre: "Drama, Action, History",
      url: "https://www.netflix.com/title/70178217",
      vid: "ULwUzF1q5w4"),
  Detail(
      title: "South Park",
      description:
          "Four young, schoolgoing boys, Stan Marsh, Kyle Broflovski, Eric Cartman and Kenny McCormick, who live in South Park set out on various adventures.",
      rating: 8.7,
      stream: "Torrent",
      status: "Ongoing",
      seasons: 23,
      genre: " Animation, Comedy ",
      url: "",
      vid: "rWCtWissSDQ"),
  Detail(
      title: "Six feet under",
      description:
          "Before Nathaniel Fisher Sr. dies, he hands over the control of his funeral home business to his sons Nathaniel Samuel Jr and David. But the brothers and the entire family are caught in a conflict.",
      rating: 8.7,
      stream: "Hotstar",
      status: "Completed",
      seasons: 5,
      genre: "Comedy, Drama",
      url: "https://www.hotstar.com/tv/six-feet-under/s-1928",
      vid: "VT6Fq1ENb8s"),
  Detail(
      title: "Shameless",
      description:
          "Frank Gallagher is the head of a working-class family in Chicago. His six children suffer because he is a heavy drinker. Fiona, the eldest daughter, looks after everyone in the house.",
      rating: 8.7,
      stream: "Prime Video",
      status: "Ongoing",
      seasons: 10,
      genre: "Comedy, Drama",
      url:
          "https://www.primevideo.com/detail/Shameless/0T621HEQUP61Z9GEB6WGJFBZO2",
      vid: "ex95FSZOT04"),
  Detail(
      title: "Dexter",
      description:
          "By day, mild-mannered Dexter is a blood-spatter analyst for the Miami police. But at night, he is a serial killer who only targets other murderers.",
      rating: 8.7,
      stream: "Hotstar",
      status: "Completed",
      seasons: 8,
      genre: " Crime, Drama, Mystery",
      url: "https://www.hotstar.com/tv/dexter/s-1187",
      vid: "x9aGJeL_BRc"),
  Detail(
      title: "Doctor Who",
      description:
          "The further adventures in time and space of the alien adventurer known as the Doctor and their companions from planet Earth.",
      rating: 8.7,
      stream: "Prime Video",
      status: "Ongoing",
      seasons: 12,
      genre: "Adventure, Drama, Family ",
      url: "https://www.primevideo.com/detail/0M2B9OJDPYPJIB6Y7IVZ5SQ2Q5",
      vid: "Gdi50ZJnE9Y"),
  Detail(
      title: "House",
      description:
          "An antisocial maverick doctor who specializes in diagnostic medicine does whatever it takes to solve puzzling cases that come his way using his crack team of doctors and his wits.",
      rating: 8.7,
      stream: "Prime Video",
      status: "Completed",
      seasons: 8,
      genre: "Drama, Mystery",
      url: "https://www.primevideo.com/detail/0JKSFB85TVXVK28OVC7CVSTQVI",
      vid: "MczMB8nU1sY"),
  Detail(
      title: "The Simpsons",
      description:
          "The satiric adventures of a working-class family in the misfit city of Springfield.",
      rating: 8.7,
      stream: "Torrent",
      status: "Ongoing",
      seasons: 32,
      genre: " Animation,Comedy",
      url: "",
      vid: "pzdnq1zFvOY"),
  Detail(
      title: "Money heist",
      description:
          "A group of very peculiar robbers assault the Factory of Moneda and Timbre to carry out the most perfect robbery in the history of Spain and take home 2.4 billion euros.",
      rating: 8.6,
      stream: "Netflix",
      status: "Ongoing",
      seasons: 3,
      genre: "Action, Crime, Mystery",
      url: "https://www.netflix.com/title/80192098",
      vid: "hMANIarjT50"),
  Detail(
      title: "Vikings",
      description:
          "Ragnar Lothbrok, a legendary Norse hero, is a mere farmer who rises up to become a fearless warrior and commander of the Viking tribes with the support of his equally ferocious family.",
      rating: 8.6,
      stream: "Netflix",
      status: "Ongoing",
      seasons: 6,
      genre: " Action, Adventure, Drama",
      url: "https://www.netflix.com/title/70301854",
      vid: "1j2sXLbzm9U"),
  Detail(
      title: "Broadwalk Empire",
      description:
          "Enoch Thompson, the treasurer of Atlantic City, is friends with mobsters and politicians alike, resulting in the federal government taking special interest in him.",
      rating: 8.6,
      stream: "Hotstar",
      status: "Completed",
      seasons: 5,
      genre: " Crime, Drama, History",
      url: "https://www.hotstar.com/tv/boardwalk-empire/s-951",
      vid: "e6z71l6HQwQ"),
  Detail(
      title: "Hannibal",
      description:
          "Will Graham, an FBI criminal profiler, has an uncanny ability to sympathise with Dr Hannibal Lecter, a forensic psychiatrist. However, he is unaware that he is a cannibal.",
      rating: 8.5,
      stream: "Netflix",
      status: "Completed",
      seasons: 3,
      genre: " Crime, Drama, Horror",
      url: "https://www.netflix.com/title/70241956",
      vid: "Sx9bjEfzV_s"),
  Detail(
      title: "The Spartacus",
      description:
          "IThe life of Spartacus, the gladiator who lead a rebellion against the Romans. From his time as an ally of the Romans, to his betrayal and becoming a gladiator, to the rebellion he leads and its ultimate outcome.",
      rating: 8.5,
      stream: "Netflix",
      status: "Completed",
      seasons: 4,
      genre: " Action, Adventure, Biography",
      url: "https://www.netflix.com/title/70136152",
      vid: "eJiBouML3FQ"),
  Detail(
      title: "Mr. Robot",
      description:
          "Elliot, a cyber-security engineer suffering from anxiety, works for a corporation and hacks felons by night. Panic strikes him after a cryptic anarchist recruits him to destroy the same corporation.",
      rating: 8.5,
      stream: "Prime Video",
      status: "Ongoing",
      seasons: 4,
      genre: " Crime, Drama, Thriller",
      url:
          "https://www.primevideo.com/detail/Mr-Robot/0ND5POOAYD6A4THTH7C1TD3TYE",
      vid: "xIBiJ_SzJTA"),
  Detail(
      title: "Suits",
      description:
          "On the run from a drug deal gone bad, Mike Ross, a brilliant college dropout, finds himself a job working with Harvey Specter, one of New York City's best lawyers.",
      rating: 8.5,
      stream: "Prime Video",
      status: "Ongoing",
      seasons: 9,
      genre: "Comedy, Drama",
      url: "https://www.primevideo.com/detail/0GM7SPOB9V9RQJ5JD27LKR4WHZ",
      vid: "85z53bAebsI"),
  Detail(
      title: "Entourage",
      description:
          "Vince, Eric, Turtle and Johnny lead an adventure-filled, lavish life when Vince's film career takes off in LA. Among other challenges, they also deal with Vince's obnoxious but hardworking agent, Ari.",
      rating: 8.5,
      stream: "Hotstar",
      status: "Completed",
      seasons: 8,
      genre: "Comedy, Drama",
      url: "https://www.hotstar.com/tv/entourage/s-1345",
      vid: "0xRHVhvhfuo"),
  Detail(
      title: "Supernatural",
      description:
          "Two brothers follow their father's footsteps as hunters, fighting evil supernatural beings of many kinds, including monsters, demons, and gods that roam the earth.",
      rating: 8.5,
      stream: "Prime Video",
      status: "Ongoing",
      seasons: 15,
      genre: " Drama, Fantasy, Horror",
      url: "https://www.netflix.com/title/70202589",
      vid: "xK7S9mrFWL4"),
  Detail(
      title: "Prison Break",
      description:
          "Due to a political conspiracy, an innocent man is sent to death row and his only hope is his brother, who makes it his mission to deliberately get himself sent to the same prison in order to break the both of them out, from the inside.",
      rating: 8.4,
      stream: "Hotstar",
      status: "Completed",
      seasons: 6,
      genre: "Action, Crime, Drama",
      url: "https://www.hotstar.com/tv/prison-break/s-564",
      vid: "AL9zLctDJaU"),
  Detail(
      title: "Brooklyn nine nine",
      description:
          "Jake Peralta, a talented detective, along with his diverse but carefree team, struggles when a new commanding officer, Ray Holt, is appointed to their precinct.",
      rating: 8.4,
      stream: "Netflix",
      status: "Ongoing",
      seasons: 7,
      genre: "Comedy, Crime",
      url: "https://www.netflix.com/title/70281562",
      vid: "sEOuJ4z5aTc"),
  Detail(
      title: "Lost",
      description:
          "The survivors of a plane crash are forced to work together in order to survive on a seemingly deserted tropical island.",
      rating: 8.4,
      stream: "Prime Video",
      status: "Completed",
      seasons: 6,
      genre: "Adventure, Drama, Fantasy ",
      url: "https://www.primevideo.com/detail/0FO5OUZCHNCTGO9127SHE4JFH7",
      vid: "0HQLeAnhGYU"),
  Detail(
      title: "Modern Family",
      description:
          "Three modern-day families from California try to deal with their kids, quirky spouses and jobs in their own unique ways, often resulting in crazy capers.",
      rating: 9.5,
      stream: "Hotstar",
      status: "Completed",
      seasons: 1,
      genre: "Drama, Action, History",
      url: "https://www.hotstar.com/tv/band-of-brothers/s-507",
      vid: "jeX4SfsC9ws"),
  Detail(
      title: "Person of Interest",
      description:
          "An ex-assassin and a wealthy programmer save lives via a surveillance AI that sends them the identities of civilians involved in impending crimes. However, the details of the crimes--including the civilians' roles--are left a mystery.",
      rating: 8.4,
      stream: "Prime Video",
      status: "Completed",
      seasons: 5,
      genre: "Crime, Drama, Action",
      url: "https://www.primevideo.com/detail/0FO3D9HZG04H7FFM58S1TUGK78",
      vid: "WYDWSNMTauQ"),
  Detail(
      title: "Sex education",
      description:
          "Socially awkward high school student Otis may not have much experience in the lovemaking department, but he gets good guidance on the topic in his personal sex ed course -- living with mom Jean, who is a sex therapist. Being surrounded by manuals, videos and tediously open conversations about sex, Otis has become a reluctant expert on the subject. When his classmates learn about his home life, Otis decides to use his insider knowledge to improve his status at school, so he teams with whip-smart bad girl Maeve to set up an underground sex therapy clinic to deal with their classmates' problems. But through his analysis of teenage sexuality, Otis realizes that he may need some therapy of his own.",
      rating: 8.4,
      stream: "NetFlix",
      status: "Ongoing",
      seasons: 1,
      genre: "Comedy, Drama",
      url: "https://www.netflix.com/in/title/80197526",
      vid: "o308rJlWKUc"),
  Detail(
      title: "Banshee",
      description:
          "Lucas Hood, an enigmatic former swindler, assumes the identity of a murdered sheriff. But haunted by his past, he finds it difficult to carry on with his devious criminal activities.",
      rating: 8.4,
      stream: "Hotstar",
      status: "Ended",
      seasons: 4,
      genre: "Action, Crime, Drama ",
      url: "https://www.hotstar.com/tv/banshee/s-519",
      vid: "VI7haj7HTCA"),
  Detail(
      title: "24",
      description:
          "Jack Bauer, Director of Field Ops for the Counter-Terrorist Unit of Los Angeles, races against the clock to subvert terrorist plots and save his nation from ultimate disaster.",
      rating: 8.4,
      stream: "Hotstar",
      status: "Completed",
      seasons: 9,
      genre: "Action, Crime, Drama",
      url: "https://www.hotstar.com/tv/24/s-922",
      vid: "7lxDREJ4vTo"),
  Detail(
      title: "Scrubs",
      description:
          "Intern John Dorian starts his medical career in a hospital crammed with unpredictable staffers and patients. His experiences teach him about the profession, friendship and life.",
      rating: 8.4,
      stream: "Torrent",
      status: "Completed",
      seasons: 9,
      genre: "Comedy, Drama",
      url: "",
      vid: "zOgb3KIJDY8"),
  Detail(
      title: "Boston Legal",
      description:
          "Drama series that follows the personal and professional exploits of a group of brilliant but often emotionally challenged attorneys. Boston Legal is a spin-off of the long-running David E. Kelley series The Practice (1997), following the exploits of former Practice character Alan Shore (James Spader) at the legal firm of Crane, Poole, and Schmidt.",
      rating: 8.4,
      stream: "Hotstar",
      status: "Ended",
      seasons: 5,
      genre: "Comedy, Crime, Drama  ",
      url: "https://www.hotstar.com/tv/boston-legal/s-144",
      vid: "9DW7jjwpa0g"),
  Detail(
      title: "Spooks",
      description:
          "A team of agents in the British security intelligence service work to protect the U.K. from terrorists and other threats to national security. A repackaged version of the BBC series 'Spooks,' 'MI-5' follows a counterterrorism unit based in the highly secure suite of offices called The Grid, where Harry Pearce oversees the team and deals with the often dirty politics of the spy game.",
      rating: 8.3,
      stream: "Torrents",
      status: "Completed",
      seasons: 10,
      genre: " Drama, Thriller",
      url: "",
      vid: "sz0mQUJxswQ"),
  Detail(
      title: "Atypical",
      description:
          "This heartfelt comedy follows Sam, a teenager on the autism spectrum, who has decided he is ready for romance. In order to start dating -- and hopefully find love -- Sam will need to be more independent, which also sends his mother (Jennifer Jason Leigh) on her own life-changing path. She and the rest of Sam's family, including a scrappy sister and a father seeking a better understanding of his son, must adjust to change and explore what it means to be 'normal.' The series is created and written by Robia Rashid and Academy Award-winning producer Seth Gordon.",
      rating: 8.3,
      stream: "Netflix",
      status: "Ongoing",
      seasons: 2,
      genre: "Comedy",
      url: "https://www.netflix.com/title/80117540",
      vid: "ieHh4U-QYwU"),
  Detail(
      title: "How I met Your mother",
      description:
          "A father recounts to his children, through a series of flashbacks, the journey he and his four best friends took leading up to him meeting their mother.",
      rating: 8.3,
      stream: "Hotstar",
      status: "Completed",
      seasons: 9,
      genre: "Comedy, Sitcom",
      url: "https://www.hotstar.com/tv/how-i-met-your-mother/s-542",
      vid: "C8-4jMTOUJI"),
  Detail(
      title: "Californication",
      description:
          "A failed writer moves to Los Angeles because his job demands him to do so. He suffers from writer's block which further complicates his relationship with his ex-girlfriend and daughter.",
      rating: 8.3,
      stream: "Netflix",
      status: "Completed",
      seasons: 7,
      genre: "Comedy, Drama",
      url: "https://www.netflix.com/title/70140366",
      vid: "gQ7yaQhXJAI"),
  Detail(
      title: "the Walking dead",
      description:
          "A group of survivors led by police officer Rick Grimes travel in search of a safe and secure home after a zombie apocalypse spreads across the USA.",
      rating: 8.3,
      stream: "Netflix",
      status: "Ongoing",
      seasons: 9,
      genre: "Drama, Horror, Thriller",
      url: "https://www.netflix.com/title/70177057",
      vid: "R1v0uFms68U"),
  Detail(
      title: "Orphan Black",
      description:
          "After witnessing the suicide of a girl who looks just like her, Sarah assumes her identity. But she soon discovers a compelling conspiracy that changes her life forever.",
      rating: 8.3,
      stream: "Netflix",
      status: "Completed",
      seasons: 5,
      genre: "Action, Drama, Sci-Fi",
      url: "https://www.netflix.com/title/70276033",
      vid: "do_BCA-vR9E"),
  Detail(
      title: "Jack Ryan",
      description:
          "An up-and-coming CIA analyst, Jack Ryan, is thrust into a dangerous field assignment as he uncovers a pattern in terrorist communication that launches him into the center of a dangerous gambit..",
      rating: 8.2,
      stream: "Prime Video",
      status: "Ongoing",
      seasons: 2,
      genre: "Action, Crime, Drama",
      url: "https://www.primevideo.com/detail/0RIEKNKOEEHUNRBHQUH436OHYU",
      vid: "1KsyZF590NM"),
  Detail(
      title: "The Good place",
      description:
          "Eleanor, a deceased saleswoman who lived a morally corrupt life, finds herself in a heaven-like afterlife in a case of mistaken identity and tries to hide her past in order to stay there.",
      rating: 8.2,
      stream: "Netflix",
      status: "Ongoing",
      seasons: 3,
      genre: " Comedy, Drama",
      url: "https://www.netflix.com/title/80113701",
      vid: "RfBgT5djaQw"),
  Detail(
      title: "Big Bang theory",
      description:
          "The lives of four socially awkward friends, Leonard, Sheldon, Howard and Raj, take a wild turn when they meet beautiful and free-spirited Penny.",
      rating: 8.2,
      stream: "Hotstar",
      status: "Completed",
      seasons: 12,
      genre: "Comedy, Sitcom",
      url: "https://www.hotstar.com/tv/the-big-bang-theory/s-1665",
      vid: "WBb3fojgW0Q"),
  Detail(
      title: "Orange is the new black",
      description:
          "Ten years after transporting drug money to Alex, Piper is imprisoned for the crime. The toughness of prison changes her drastically as an individual, compelling her to do the unthinkable.",
      rating: 8.1,
      stream: "Netflix",
      status: "Ongoing",
      seasons: 6,
      genre: " Crime, Comedy",
      url: "https://www.netflix.com/title/70242311",
      vid: "vY0qzXi5oJg"),
  Detail(
      title: "American Horror Story",
      description:
          "An anthology of stories consisting of a house with a deadly secret, a demented asylum, a witch coven, an unusual show, a hotel, a haunted farmhouse, a cult and an apocalypse.",
      rating: 8.1,
      stream: "Hotstar",
      status: "Ongoing",
      seasons: 8,
      genre: " Mystery,Suspense,Chilling",
      url: "https://www.hotstar.com/tv/american-horror-story/s-556",
      vid: "9KZr2Vn7CQ"),
  Detail(
      title: "End Of The F***king World",
      description:
          "Based on the comic book series by Charles Forsman, \"The End of the F***ing World\" sees two 17-year-old outsiders, James and Alyssa, embark on a road trip to find her estranged father, who left home when she was just a child. James, who is convinced he's a psychopath, has decided it's time to graduate from killing animals to something bigger -- and he already has a target in mind. Alyssa, the embodiment of existential angst, feels like she doesn't fit in at her new school despite being quite popular. Together, they get caught up on a trail of violent events that grow increasingly more ominous as their quest progresses.",
      rating: 8.1,
      stream: "NetFlix",
      status: "Ongoing",
      seasons: 2,
      genre: " Adventure, Comedy, Crime ",
      url: "https://www.netflix.com/title/80175722",
      vid: "aV-y3bvYFYA"),
  Detail(
      title: "13 Reasons Why",
      description:
          "Newcomer Katherine Langford plays the role of Hannah, a young woman who takes her own life. Two weeks after her tragic death, a classmate named Clay finds a mysterious box on his porch. Inside the box are recordings made by Hannah -- on whom Clay had a crush -- in which she explains the 13 reasons why she chose to commit suicide. If Clay decides to listen to the recordings, he will find out if and how he made the list. This intricate and heart-wrenching tale is told through Clay and Hannah's dual narratives.",
      rating: 8.0,
      stream: "Netflix",
      status: "Ongoing",
      seasons: 2,
      genre: "Drama, Mystery",
      url: "https://www.netflix.com/title/80117470",
      vid: "toj3CyMhBOs"),
];
